/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brown: {
          50: '#f5ece7', 100: '#efe6e2', 200: '#e1d8d4',
          300: '#d2c4ba', 400: '#bd9f83', 500: '#80756c',
          600: '#725a42', 700: '#4b3621', 800: '#33210d',
          900: '#1e1b18',
        },
        ds: {
          surface: '#fff8f5',
          'surface-dim': '#e1d8d4',
          'surface-bright': '#fff8f5',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#fbf2ed',
          'surface-container': '#f5ece7',
          'surface-container-high': '#efe6e2',
          'surface-container-highest': '#e9e1dc',
          'on-surface': '#1e1b18',
          'on-surface-variant': '#4e453d',
          'inverse-surface': '#34302c',
          'inverse-on-surface': '#f8efea',
          outline: '#80756c',
          'outline-variant': '#d2c4ba',
          'surface-tint': '#725a42',
          primary: '#33210d',
          'on-primary': '#ffffff',
          'primary-container': '#4b3621',
          'on-primary-container': '#bd9f83',
          'inverse-primary': '#e1c1a4',
          secondary: '#5e604d',
          'on-secondary': '#ffffff',
          'secondary-container': '#e1e1c9',
          'on-secondary-container': '#636451',
          tertiary: '#002c06',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#00450e',
          'on-tertiary-container': '#56b958',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#fedcbe',
          'primary-fixed-dim': '#e1c1a4',
          'on-primary-fixed': '#291806',
          'on-primary-fixed-variant': '#59422c',
          'secondary-fixed': '#e4e4cc',
          'secondary-fixed-dim': '#c8c8b0',
          'on-secondary-fixed': '#1b1d0e',
          'on-secondary-fixed-variant': '#474836',
          'tertiary-fixed': '#94f990',
          'tertiary-fixed-dim': '#78dc77',
          'on-tertiary-fixed': '#002204',
          'on-tertiary-fixed-variant': '#005313',
          'surface-variant': '#e9e1dc',
          background: '#fff8f5',
          'on-background': '#1e1b18',
        }
      },
      fontFamily: {
        serif: ['Literata', 'serif'],
        sans: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
